### PR TITLE
Fix cargo worksapce test with --no-fail-fast

### PR DESCRIPTION
**Pull request by gen-xu**
Addressing https://github.com/xd009642/tarpaulin/issues/1229

Allow workspace test binaries loop to continue if `--no-fail-fast` is provided

### CODE REVIEW

**Comment by gen-xu** [comment]
I guess one question I have here is that when we have `--no-fail-fast` on, do we still want tarpaulin to output test coverage or not, and should it have 0 exiting code or non-0 exiting code? IMO it makes sense to have non-0 exiting code but output coverage but I would like to hear more opinions.

**Comment by xd009642** [comment]
>  IMO it makes sense to have non-0 exiting code but output coverage but I would like to hear more opinions. 

That makes the most sense to me as well, so no dissenting opinions here :+1:

**Comment by xd009642** [comment]
Hi @gen-xu mild poke do you plan on finishing this off sometime soon? If you're too busy I should hopefully have some free bandwidth to push it over the line next week

**Comment by gen-xu** [comment]
> Hi @gen-xu mild poke do you plan on finishing this off sometime soon? If you're too busy I should hopefully have some free bandwidth to push it over the line next week

I think the efforts needed was than I expected so I have been leaving it off for a while. Yeah, if you have somed bandwidth for this it would be great. Thanks!

**Pull request closed without merging**
