### PR TITLE
calculate relative paths to base_dir (env::current_dir(), or root arg)

### PR DESCRIPTION
**Pull request by PSeitz**
ignore lines containing "}else{"
add --manifest-path option

### CODE REVIEW

**Comment by xd009642** [comment]
Cool I'll have to check this over just to make sure I'm happy but a brief skim it looks good. I recently added a changelog to the project could you also update that :+1:

**Comment by PSeitz** [comment]
Sure, I added the changes to the changelog.
I added "Use relative file paths to base_dir" under #Changed, but the behaviour should be the same. There are only differences in the path with the manifest-path option.

**Comment by xd009642** [comment]
So I'm not sure if this works as expected, given a manifest path in a different directory:

```
cargo run -- tarpaulin --manifest-path tests/data/simple_project/Cargo.toml 
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/cargo-tarpaulin tarpaulin --manifest-path tests/data/simple_project/Cargo.toml`
Error: "Failed to parse Cargo.toml! Error: invalid path url `tests/data/simple_project`"
```

Also, it seems like it would be simpler to not add the manifest member into the config struct or remove root as they're basically just the same data but the types are different and one has the `Cargo.toml` appended to the path. And if the project root isn't set but the manifest-dir is this could create errors due to the redundant information

**Comment by PSeitz** [comment]
Whoops, I fixed it. I tested the wrong branch. I think there might be a case where someone wants to use both, have paths calculated relative to root, but still use different manifest-paths. What do you think?

There are some things, which are weird:
Coverage in coveralls is wrong for `rocket_server.rs`. The test run from the root folder ignores most of the lines, which are still ignored when merged:
https://coveralls.io/builds/25207759
When I execute only the tests in the server directory, the coverage looks fine.
https://coveralls.io/builds/25209623

In Codecov, the merge looks fine:
https://codecov.io/gh/PSeitz/veloci/tree/a9f7d6f49f976f2fdc7c205ff1c799d639953d42

**Comment by PSeitz** [comment]
Also, root and manifest-path are not the same, since only root affects the calculation of the base_dir.

**Comment by xd009642** [comment]
> Also, root and manifest-path are not the same, since only root affects the calculation of the base_dir.

So in that case the help text should be amended for `--root` maybe mention that if a separate manifest dir isn't specified it will look for the manifest at the location in `--root`

**Comment by xd009642** [comment]
However, apart from that (and the pending changelog update) it all looks good

**Comment by PSeitz** [comment]
I updated the PR

**Comment by xd009642** [comment]
Awesome, I'll merge it in now :+1:

**Pull request merged**
