### PR TITLE
Coverage change added to HTML report

### PR DESCRIPTION
**Pull request by bojan88**
Coverage change for files in the report
Implementation for https://github.com/xd009642/tarpaulin/issues/284

Screenshot

### CODE REVIEW

**Comment by xd009642** [comment]
Awesome, just let me try it out and have a look at the code :+1:

**Comment by xd009642** [comment]
No issues here, if you update the changelog I'll merge it :+1:

**Comment by bojan88** [comment]
Sorry, I keep forgetting to update changelog.
Let me know if you want me to make more changes before merging

**Comment by xd009642** [comment]
It's alright I always do it last anyway. And that's all good so merging now 👍

**Pull request merged**
