### PR TITLE
bump quick-xml to v0.12.1

### PR DESCRIPTION
**Pull request by tafia**
cargo-tarpaulin is targeting version 0.9.0 only. 

The main changes for you are some bug fixes plus the use of failure instead of error-chain.

### CODE REVIEW

**Comment by xd009642** [comment]
Hi, firstly thanks for the PR. However, tarpaulin does work off the develop branch and only commits releases and README changes that are important for users between releases on master. The current version of quick-xml used by the latest develop build is 0.11.* so it does still need updating though.

If you take the latest version on the develop branch and apply the change I'll merge it in. Also, if you're willing there are some more outdated packages. Output of `cargo outdated -d 1` is as follows:

```
Name            Project  Compat  Latest  Kind    Platform
----            -------  ------  ------  ----    --------
cargo           0.24.0   ---     0.25.0  Normal  ---
clap            2.29.4   2.31.2  2.31.2  Normal  ---
libc            0.2.36   0.2.39  0.2.39  Normal  ---
quick-xml       0.11.0   ---     0.12.1  Normal  ---
regex           0.2.6    0.2.10  0.2.10  Normal  ---
rustc-demangle  0.1.5    0.1.7   0.1.7   Normal  ---
serde           1.0.27   1.0.34  1.0.34  Normal  ---
serde_json      1.0.9    1.0.13  1.0.13  Normal  ---
```

**Comment by tafia** [comment]
I'll do this this weekend!

**Comment by xd009642** [comment]
Awesome, thank you :+1:

**Comment by xd009642** [comment]
Hi @tafia any work on this? Just checking because a moderately large PR may be merged in before the end of the week so it may be easier for you if you get in quick :smile:

**Comment by tafia** [comment]
Sorry I forgot.
I'm on it right now.

**Comment by tafia** [comment]
close #97

**Pull request closed without merging**
