### PR TITLE
GitHub actions

### LINKED ISSUE #257: migration ci from travis to github actions
Github action is a beta service of github(https://github.com/features/actions) and already available for signup. It provides more executors for the projects.

Can this project be migrated to github actions?

I can start this initiative, but it requires to enable actions for the repository.

### PR DESCRIPTION
**Pull request by AnderEnder**
closes #257

* remove travis configuration
* add rust build-ci configuration: .github/workflows/rust.yml 
* add release configuration: .github/workflows/release.yml

TODO:
- add travis token as secret with name `CARGO_TOKEN` in order to release crate
- add docker hub token with name `DOCKER_TOKEN`
- verify release binary, because it may require a different libc library for travis environment(ubuntu 14.04), so maybe a release build with musl static link is required.

### CODE REVIEW

**Comment by AnderEnder** [comment]
Looks like PR from fork does not run github actions, so it is better to check it on local branch and PR from it.

Example of running actions: https://github.com/AnderEnder/tarpaulin/commits/github-actions and https://github.com/AnderEnder/tarpaulin/pull/1

**Comment by xd009642** [comment]
So only just initially looked at this (finally). One thing immediately stands out that there's no more call to the script to trigger the docker hub builds. Otherwise it looks like it should be good

**Comment by AnderEnder** [comment]
@xd009642, added a new step and updated TODO description.

**Comment by xd009642** [comment]
Right just so I can make sure this works before fully switching I'm going to merge it into a branch called actions. If it doesn't work I'll then create an issue and tag you in it if it's not immediately evident to me :+1:

**Pull request merged**
