### PR TITLE
fix: coveralls report on windows

### LINKED ISSUE #1448: "Source Not Available" Error on Coveralls
**Describe the bug**
Looks like the coverage report sent to Coveralls fails to match with the GitHub files. Here is [an example](https://coveralls.io/builds/64909643/source?filename=bin%5Csrc%5Cmain.rs) on my project.

**To Reproduce**

1. Fetch [my project](https://github.com/drsanguin/convertible_couch)
2. Install Tarpaulin:
    ```
    cargo install cargo-tarpaulin
    ```
4. Run tarpaulin on my project
    ```
    cargo tarpaulin --coveralls Z53FpI2gSTvnQw64wGeSx1aX0u5M1PEV5
    ```
    Don't be shy of pushing coverage to the coveralls project. I will regenerate the token later.
5. Go to [the repository page](https://coveralls.io/github/drsanguin/convertible_couch) on coveralls to see the error

Please note that this will allow you to reproduce the issue on local. On my project, I send coverage report using [this GitHub Action](https://github.com/drsanguin/convertible_couch/blob/main/.github/workflows/ci.yml#L39-L48). Error is the same in both ways.

**Expected behavior**
The source on Coveralls should match the GitHub's ones.

**Environment**
- OS: windows
- Cargo: 1.72.0 (103a7ff2e 2023-08-15)
- tarpaulin: 0.27.2

**Additional intel**
- traces of `--dump-traces` parameter: [tarpaulin_20240106135336.json](https://github.com/xd009642/tarpaulin/files/13849786/tarpaulin_20240106135336.json)
- coverage file: [coverage.json](https://github.com/xd009642/tarpaulin/files/13849787/coverage.json)

**My two cents on the rootcause**
Since I work on windows, I believe the report is send to Coveralls with the Windows path separator `\` and Coveralls search files in the repo with the linux one `/`.

Thanks in advance for the help !

### PR DESCRIPTION
**Pull request by drsanguin**
Coveralls expect source path to have the Linux path separator. Otherwise, it cannot link them with the repository's source.

Fixes #1448

### CODE REVIEW

**Comment by xd009642** [comment]
Cools thanks for this - I was gonna get to it this weekend hopefully but this saves me some word :pray: . I'll merge tomorrow if CI (minus windows) has passed

**Comment by drsanguin** [comment]
> Cools thanks for this - I was gonna get to it this weekend hopefully but this saves me some word 🙏 . I'll merge tomorrow if CI (minus windows) has passed

You're welcome ! There was some formatting issues. I fixed them all !

What is wrong with the Windows CI ?

**Comment by xd009642** [comment]
Something weird in an llvm coverage update, I haven't had time to look properly yet. Work's been busy and I'm also preparing my talk for rustnation in march so I haven't had any free spoons for tarpaulin

**Comment by drsanguin** [comment]
No worries ! I think we are all busy at some point.

By the way it seems that you need to trigger the workflows again.

**Comment by drsanguin** [comment]
So is it ok regarding the CI results ?

**Comment by xd009642** [comment]
Yeah all good, merging now :+1:

**Pull request merged**
