### PR TITLE
Feature/take in compilation target

### PR DESCRIPTION
**Pull request by azriel91**
Heya, some projects compile to different compilation targets, and so need a way to wire that through to `cargo`. This PR adds that functionality, so users can now go:

```bash
cargo tarpaulin --target x86_64-linux-gnu
```

or in `tarpaulin.toml`:

```toml
[linux_32]
target = "x86-linux-gnu"

[linux_64]
target = "x86_64-linux-gnu"
```

### CODE REVIEW

**Comment by xd009642** [comment]
So tarpaulin is only expected to work on x86_64 Linux, I'm not against this as a change just wondering how practically useful it is?

**Comment by azriel91** [comment]
oh, tarpaulin still runs on x86_64 linux, this is for the compilation target, i.e. if you're cross compiling for different destinations, and would like to test different code paths based on that.

So for example if building for a 32 bit system, you want to take a different code path (perhaps it's more optimal).

**Comment by xd009642** [comment]
Ah okay then that sounds fine, and the code looks good too. If you update the changelog I'll merge it in :+1:

**Comment by azriel91** [comment]
:v: cool thanks!

**Pull request merged**
