### PR TITLE
update linux.rs

### PR DESCRIPTION
**Pull request by ZRSAFD**
Optimization: If ASLR is already turned off, the disable_aslr() function will no longer be called.
This can expand the usage scenarios of tarpaulin. For example, after the root permission administrator shuts down the server ASLR, ordinary users can still use tarpaulin normally even if they cannot obtain root permission~

### CODE REVIEW

**Comment by xd009642** [comment]
Cool code looks fine from a brief skim. I'm abroad right now so I'm look properly on Monday when I'm back home

**Comment by ZRSAFD** [comment]
thank you,tarpaulin has been a great help to me~  \(^o^)/

**Review by xd009642 — APPROVED** [review]

**Comment by ZRSAFD** [comment]
Hello~ May I ask if it is convenient for you to publish the latest tarpaulin code on [http://cartes.io](https://t.co/XwHh1UzjmA) recently? I want to try out the new features XD @xd009642

**Comment by xd009642** [comment]
Sure I'll do a release this weekend or Monday

**Comment by xd009642** [comment]
And release is done, only a day later than planned :sweat_smile:

**Pull request merged**
