### PR TITLE
Feature segmentation for reporter modules

### PR DESCRIPTION
**Pull request by onalante-msft**
This PR started as an experiment to remove `chrono` due to a regression introduced by 0.4.20. It has grown into a larger effort to separate the output report formats into isolated features.

### CODE REVIEW

**Comment by onalante-msft** [comment]
Marked as draft since there is still work to be done on gating the reporter modules behind feature flags. However, I am open to comments on the current changes.

**Comment by xd009642** [comment]
Cool, I'll try to have a look at this during the week, there does appear to be a lot of changes in different areas so if you don't mind splitting the ptrace stuff into a separate PR that would be helpful :pray:

**Comment by onalante-msft** [comment]
I split off the ptrace code to #1067. I have marked it as a draft to prevent it from getting merged as it still has a failing test that needs debugging.

**Comment by onalante-msft** [comment]
Sorry about not following up on this. I am going to close this PR since A. chrono fixed its regression, and B. the upstream reporter modules are not a significant source of build slowdown in the grand scheme of things. If you are still interested in exposing the reporter modules as feature flags, I updated the code from this PR at https://github.com/onalante/tarpaulin/tree/feature-segmentation.

**Pull request closed without merging**
