### PR TITLE
Initial version of HTML report

### PR DESCRIPTION
**Pull request by andy128k**
Related to https://github.com/xd009642/tarpaulin/issues/55

### CODE REVIEW

**Comment by xd009642** [comment]
There's already work on this in the `issue_55` branch which is a big overhaul of the whole reporting system to make it easier to add new reports in future. So I'd kind of prefer any work to be a continuation of the existing work.

**Comment by AnderEnder** [comment]
@xd009642,

Looks like `issue_55` branch is unfinished and it does not look like there is a big progress over the time.

Moreover this PR's implementation is much simpler, cleaner and uses more modern web approach. And it is already ready to use.

I would suggest to use this implementation as a base for HTML reports.

**Comment by xd009642** [comment]
@andy128k if you sort the `Cargo.lock` merge conflict I'll merge this PR. 

Issue_55 did add things like source_tree for folder based browsing of the project similar to what you see with coveralls or codecov and syntax highlighting but also was reworking all the report types to make them more testable so was turning into a monster that I cba to finish. Some parts of it are definitely worth taking but I'll work on moving them over in smaller more manageable chunks later on

**Comment by andy128k** [comment]
folders are added

**Comment by xd009642** [comment]
merging now!

**Pull request merged**
